export const constants = {
  SET_SELECTED_FEATURE: 'SELECTED_FEATURE',
  SET_POPUP_STATE: 'SETTING_POPUP_STATE',
  SET_MAP_STYLE: 'SETTING_MAP_STYLE',
  SET_ORIGIN_LAYER: 'SET_ORIGIN_LAYER',
  SET_ASSET_POINT_LAYER: 'SETTING_ASSET_POINT_LAYER',
}
