export const SETTING_MAP_LAYER = 'SETTING_MAP_LAYER'
export const SETTING_ORIGINAL_LAYER = 'SETTING_ORIGINAL_LAYER'
export const SETTING_SELECTED_FEATURE = 'SETTING_SELECTED_FEATURE'
export const SETTING_OVERLAY = 'SETTING_OVERLAY'
